version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "443:443"
    env_file:
      - ./backend/.env
    environment:
      - PORT=443
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=https://easygenerator-task.vercel.app/
      - MONGODB_URI=mongodb+srv://ahmed7sn3amer:Ahmed%40123@easygenerator.2mnrvsg.mongodb.net/?retryWrites=true&w=majority&appName=easygenerator

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://13.48.131.154:443