version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      - PORT=3001
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=http://13.48.131.154:3000

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://13.48.131.154:3001